# azure-pipelines.yml

parameters:
- name: option
  displayName: Option
  type: string
  default: stressOptions
  values:
  - stressOptions
  - smokeOptions

pool:
  vmImage: 'ubuntu-latest'

steps:
  - pwsh: |
      ls
  - task: k6-load-test@0
    inputs:
      filename: '003_basic_test/http_get.js'
